### ISSUE TITLE
Utils.GetAllElements should support  elements in the first level

### ISSUE THREAD

**Issue by jluzny** [daudus/SparxEAJSScripts#1]
Should support  elements in the first level

**Comment by daudus** [comment]
Hmm ... a dela i rekurzi (tedy do podslozek) nebo jen tu prvni vrstvu a ignoruje sub packages?
A vleze i do OWNED elementu?

**Comment by jluzny** [comment]
Hmm, tak to nemůžu nasimulovat. U mne to čte vše jak očekáváno tzn.:
- elementy přímo z vybraného package
- sub packages
- owned elemety

**Comment by daudus** [comment]
Divný .... nějaký nápad co debugovat?

**Comment by daudus** [comment]
Vyreseno instalaci (soubeznou) Sparx EA verze 12.1
